### ISSUE TITLE
【主页】wakw.yml

### ISSUE THREAD

**Issue by kurisaW** [kurisaW/KurisaW#16]
```yml
name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE : "False"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_LANGUAGE_PER_REPO : "False"
          SHOW_LOC_CHART : "False"
          SHOW_SHORT_INFO : "False"
          SHOW_PROJECTS : "False"
          SHOW_TOTAL_CODE_TIME : "False"
          SHOW_TITLE : true

```
